env:
  - DB_TYPE=sqlite

jobs:
  include:
    - name: Lint Python
      language: python
      python: 3.7
      install:
        - pip install .
	- git clone https://github.com/alan-turing-institute/plark_ai_public.git
	- cd plark_ai_public/Components/plark-game; pip install . ; cd -;
      script: flake8 . --statistics --count
      script: pytest --ignore-glob='plark_ai_public/*
