version: '3'
services:
  messages:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
    - "5672:5672"
    networks:
    - plark_nw

  battleground:
    container_name: plark_battleground
    image: turingrldsg.azurecr.io/battleground:latest
    environment:
    - RABBITMQ_HOST=rabbitmq
    - MATCH_ID=19
    - NO_DB_TEST=True
    networks:
    - plark_nw
    tty: true
    depends_on:
      - messages
    command: "./run_match.sh"

  pelican:
    container_name: pelican_agent
    image: turingrldsg.azurecr.io/team_test_1:pelican_latest

    environment:
    - RABBITMQ_HOST=rabbitmq
    networks:
    - plark_nw
    tty: true
    depends_on:
    - messages
    command: "python3 Combatant/combatant.py pelican"


  panther:
    container_name: panther_agent
    image: turingrldsg.azurecr.io/team_test:panther_agent_move_north
    environment:
    - RABBITMQ_HOST=rabbitmq
    networks:
    - plark_nw
    tty: true
    depends_on:
    - messages
    command: "python3 Combatant/combatant.py panther"

networks:
  plark_nw:
    driver: bridge
