version: '3'
services:
  messages:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
    - "5672:5672"
    networks:
    - plark_nw

  battleground:
    container_name: plark_battleground
    image: turingrldsg0309.azurecr.io/battleground:test_no_db
    environment:
    - RABBITMQ_HOST=rabbitmq
    - MATCH_ID=0
    - NO_DB_TEST=True
    - CONFIG_FILE=/rl_tournament/2021_03_09_06_28x26_02_08_24_13.json
    - NUM_GAMES=1
    networks:
    - plark_nw
    tty: true
    depends_on:
      - messages
    command: "./run_match.sh"

  pelican:
    container_name: pelican_agent
    image: turingrldsg0309.azurecr.io/team_test:pelican_agent_any_size
    environment:
    - RABBITMQ_HOST=rabbitmq
    networks:
    - plark_nw
    tty: true
    depends_on:
    - messages
    command: "python3 Combatant/combatant.py pelican"


  panther:
    container_name: panther_agent
    image: turingrldsg0309.azurecr.io/team_test:panther_agent_move_north
    environment:
    - RABBITMQ_HOST=rabbitmq
    networks:
    - plark_nw
    tty: true
    depends_on:
    - messages
    command: "python3 Combatant/combatant.py panther"

networks:
  plark_nw:
    driver: bridge
