version: '3'
services:
  messages:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
    - "5672:5672"
    networks:
    - plark_nw

  battleground:
    container_name: plark_battleground
    build:
      context: .
      dockerfile: Dockerfile_battleground
    environment:
    - RABBITMQ_HOST=rabbitmq
    - MATCH_ID=<MATCH_ID>
    - NUM_GAMES=<NUM_GAMES>
    networks:
    - plark_nw
    tty: true
    depends_on:
      - messages
      - pelican
      - panther
    command: "./run_match.sh"

  pelican:
    container_name: pelican_agent
    image: <PELICAN_IMAGE>
    environment:
    - RABBITMQ_HOST=rabbitmq
    networks:
    - plark_nw
    tty: true
    depends_on:
    - messages
    command: "python3 Combatant/combatant.py pelican"


  panther:
    container_name: panther_agent
    image: <PANTHER_IMAGE>
    environment:
    - RABBITMQ_HOST=rabbitmq
    networks:
    - plark_nw
    tty: true
    depends_on:
    - messages
    command: "python3 Combatant/combatant.py panther"


networks:
  plark_nw:
    driver: bridge
